baseURL = "https://elsabonnaud.fr"
languageCode = "en-us"
title = "Elsa Bonnaud"
theme = "m10c"
defaultContentLanguage = "en-us"

[params]
    author = "Elsa Bonnaud"
    avatar = "/avatar.jpg"
    description = "MCF Lecturer"
    menu_item_separator = "<br/>"

